name: Automated API tests using Newman collection
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:
jobs:
  test-e2e-api:
        name: Run nightly
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            # Creates an artifact folder in workflow folder
          # run: mkdir TestArtifact
            # Install node on the runn
          - name: Install node
            uses: actions/setup-node@v4
            with: 
              node-version: '20.x'
            # Install newman globally
          - name: Install newman
            run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
            # Run tests
          - name: Run tests
            run : newman run "postman_collection.json" -r htmlextra --reporter-htmlextra-export testresults/htmlreport.html
          # Create  test directory
          - name: Create test results directory
            run: mkdir -p test-results
          - name: Output results 
            uses: actions/upload-artifact@v4
            with:
             name: Test Results
             path: test-results
