name: Automated API tests using Newman collection

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  test-e2e-api:
    name: Run nightly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and Newman
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Newman and HTML Extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run API tests
        run: newman run "postman_collection.json" -r htmlextra --reporter-htmlextra-export test-results/htmlreport.html

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results

      - name: Send test results to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "API test results are available at https://app.slack.com/test-results/htmlreport.html"
          channel: "#qa-channel"
